runtime: php81



# この記載がないとcssとjsがnot foundになるので必須
handlers:
# Serve a directory as a static resource.
- url: /css
  static_dir: public/css
- url: /js
  static_dir: public/js


env_variables:
  APP_KEY: base64:Nj/jHztecjw3kiP5SktbiJvLsIT7OVDEPz3gdRQS14E=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  CACHE_DRIVER: database

    ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: salary
  DB_USERNAME: root
  DB_PASSWORD: 1036746t
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/redroof-salary:asia-east2:redroof-salary"
  ## for PostgreSQL, use DB_HOST: